src/Entity/Inspection.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InspectionRepository")
 */
class Inspection
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $RoadId;

    /**
     * @ORM\Column(type="text")
     */
    private $Note;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $RepairDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Username;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DoneJobs", mappedBy="inspection", cascade={"persist"})
     */
    private $Job;

    /**
     * @ORM\Column(type="float")
     */
    private $RoadSectionBegin;

    /**
     * @ORM\Column(type="float")
     */
    private $RoadSectionEnd;

    /**
     * @ORM\Column(type="integer")
     */
    private $SubUnitId;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsAdditional;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $RoadCondition;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $WaveSize;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Place;


    public function __construct()
    {
        $this->Job = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getRoadId(): ?string
    {
        return $this->RoadId;
    }

    public function setRoadId(string $RoadId): self
    {
        $this->RoadId = $RoadId;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->Note;
    }

    public function setNote(string $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getRepairDate(): ?\DateTimeInterface
    {
        return $this->RepairDate;
    }

    public function setRepairDate(?\DateTimeInterface $RepairDate): self
    {
        $this->RepairDate = $RepairDate;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection|DoneJobs[]
     */
    public function getJob(): Collection
    {
        return $this->Job;
    }

    public function addJob(DoneJobs $job): self
    {
        if (!$this->Job->contains($job)) {
            $this->Job[] = $job;
            $job->setInspection($this);
        }

        return $this;
    }

    public function removeJob(DoneJobs $job): self
    {
        if ($this->Job->contains($job)) {
            $this->Job->removeElement($job);
            // set the owning side to null (unless already changed)
            if ($job->getInspection() === $this) {
                $job->setInspection(null);
            }
        }

        return $this;
    }

    public function getRoadSectionBegin(): ?string
    {
        return $this->RoadSectionBegin;
    }

    public function setRoadSectionBegin(string $RoadSectionBegin): self
    {
        $this->RoadSectionBegin = $RoadSectionBegin;

        return $this;
    }

    public function getRoadSectionEnd(): ?string
    {
        return $this->RoadSectionEnd;
    }

    public function setRoadSectionEnd(string $RoadSectionEnd): self
    {
        $this->RoadSectionEnd = $RoadSectionEnd;

        return $this;
    }

    public function getSubUnitId(): ?int
    {
        return $this->SubUnitId;
    }

    public function setSubUnitId(int $SubUnitId): self
    {
        $this->SubUnitId = $SubUnitId;

        return $this;
    }

    public function getIsAdditional(): ?bool
    {
        return $this->IsAdditional;
    }

    public function setIsAdditional(bool $IsAdditional): self
    {
        $this->IsAdditional = $IsAdditional;

        return $this;
    }

    public function getRoadCondition(): ?string
    {
        return $this->RoadCondition;
    }

    public function setRoadCondition(?string $RoadCondition): self
    {
        $this->RoadCondition = $RoadCondition;

        return $this;
    }

    public function getWaveSize(): ?string
    {
        return $this->WaveSize;
    }

    public function setWaveSize(?string $WaveSize): self
    {
        $this->WaveSize = $WaveSize;

        return $this;
    }

    public function getPlace(): ?float
    {
        return $this->Place;
    }

    public function setPlace(?float $Place): self
    {
        $this->Place = $Place;

        return $this;
    }
    
}

src/Entity/LdapUser.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LdapUserRepository")
 */
class LdapUser
{

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Unit", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unit;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Subunit", inversedBy="ldapUsers")
     */
    private $Subunit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Role = 'WORKER';

    /**
     * @ORM\Column(type="integer")
     */
    private $Inspection = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $DoneJobs = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $Restrictions = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $Winter = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $InsuredEvent = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $Reports = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $Flood = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $ContractJobs =1;

    public function getInspection(): ?int
    {
        return $this->Inspection;
    }

    public function setInspection(int $Inspection): self
    {
        $this->Inspection = $Inspection;

        return $this;
    }

    public function getDoneJobs(): ?int
    {
        return $this->DoneJobs;
    }

    public function setDoneJobs(int $DoneJobs): self
    {
        $this->DoneJobs = $DoneJobs;

        return $this;
    }

    public function getRestrictions(): ?int
    {
        return $this->Restrictions;
    }

    public function setRestrictions(int $Restrictions): self
    {
        $this->Restrictions = $Restrictions;

        return $this;
    }

    public function getWinter(): ?int
    {
        return $this->Winter;
    }

    public function setWinter(int $Winter): self
    {
        $this->Winter = $Winter;

        return $this;
    }

    public function getInsuredEvent(): ?int
    {
        return $this->InsuredEvent;
    }

    public function setInsuredEvent(int $InsuredEvent): self
    {
        $this->InsuredEvent = $InsuredEvent;

        return $this;
    }

    public function getReports(): ?int
    {
        return $this->Reports;
    }

    public function setReports(int $Reports): self
    {
        $this->Reports = $Reports;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        $this->Role = $Role;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUnit(): ?Unit
    {
        return $this->unit;
    }

    public function setUnit(?Unit $unit): self
    {
        $this->unit = $unit;
        return $this;
    }

    public function getSubunit(): ?Subunit
    {
        return $this->Subunit;
    }

    public function setSubunit(?Subunit $Subunit): self
    {
        $this->Subunit = $Subunit;

        return $this;
    }

    public function getFlood(): ?int
    {
        return $this->Flood;
    }

    public function setFlood(int $Flood): self
    {
        $this->Flood = $Flood;

        return $this;
    }

    public function getContractJobs(): ?int
    {
        return $this->ContractJobs;
    }

    public function setContractJobs(int $ContractJobs): self
    {
        $this->ContractJobs = $ContractJobs;

        return $this;
    }
}

src/Entity/Region.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegionRepository")
 */
class Region
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $RegionName;

    /**
     * @ORM\Column(type="integer")
     */
    private $SubunitId;

    public function getId()
    {
        return $this->id;
    }

    public function getRegionName(): ?string
    {
        return $this->RegionName;
    }

    public function setRegionName(string $RegionName): self
    {
        $this->RegionName = $RegionName;

        return $this;
    }

    public function getSubunitId(): ?int
    {
        return $this->SubunitId;
    }

    public function setSubunitId(int $SubunitId): self
    {
        $this->SubunitId = $SubunitId;

        return $this;
    }
}

src/Entity/Structure.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StructureRepository")
 */
class Structure
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Master;

    public $array = array();

    /**
     * @ORM\Column(type="integer")
     */
    private $InformationType;

    /**
     * @ORM\Column(type="integer")
     */
    private $StructureId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getMaster(): ?string
    {
        return $this->Master;
    }

    public function setMaster(string $Master): self
    {
        $this->Master = $Master;

        return $this;
    }

    public function getInformationType(): ?int
    {
        return $this->InformationType;
    }

    public function setInformationType(int $InformationType): self
    {
        $this->InformationType = $InformationType;

        return $this;
    }

    public function getStructureId(): ?int
    {
        return $this->StructureId;
    }

    public function setStructureId(int $StructureId): self
    {
        $this->StructureId = $StructureId;

        return $this;
    }

}

src/Entity/Worker.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkerRepository")
 */
class Worker
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Subunit", inversedBy="workers")
     * @ORM\JoinColumn(nullable=false)
     */

    private $Subunit;

    /**
     * @ORM\Column(type="integer")
     */
    private $WorkerId;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSubunit(): ?Subunit
    {
        return $this->Subunit;
    }

    public function setSubunit(?Subunit $Subunit): self
    {
        $this->Subunit = $Subunit;

        return $this;
    }

    public function getWorkerId(): ?int
    {
        return $this->WorkerId;
    }

    public function setWorkerId(int $WorkerId): self
    {
        $this->WorkerId = $WorkerId;

        return $this;
    }

}

src/Form/StructureType.php
<?php

namespace App\Form;

use App\Entity\Structure;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StructureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Master', ChoiceType::class, array(
                'choices' => $options['master_choice']
            ))
            ->add('InformationType', ChoiceType::class, array(
                'choices' => $options['information_choice']
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Structure::class,
            'master_choice' => array(),
            'information_choice' => array(),
        ]);
    }
}

templates/structure/_delete_form.html.twig
{% trans_default_domain 'translation' %}

<form method="post" action="{{ path('mechanism_delete', {'id': mechanism.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mechanism.id) }}">
    <button class="btn btn-danger btn-lg">{% trans %}Delete{% endtrans %}</button>
</form>

templates/structure/_form.html.twig
{% trans_default_domain 'translation' %}

{{ form_start(form) }}

    {{ form_widget(form) }}
    <button id="save_button" class="btn btn-success btn-lg">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/structure/edit.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'translation' %}

{% block title %}{% trans %}Edit structure{% endtrans %}{% endblock %}

{% block body %}
    <h1>{% trans %}Edit structure{% endtrans %}</h1>

    {{ include('structure/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary btn-lg" href="{{ path('structure_index') }}">{% trans %}back to list{% endtrans %}</a>

    {{ include('structure/_delete_form.html.twig') }}
{% endblock %}

templates/structure/macros.html.twig
{% macro recursiveCategory(entity) %}
    {% import _self as self %}
        {% if entity.array|length %}
            <ul>
                {% for child in entity.array %}
                    <ul>
                    <a>{{ child.Name }}</a>

                    {{ self.recursiveCategory(child) }}
                    </ul>
                {% endfor %}
            </ul>
        {% endif %}
{% endmacro %}

templates/structure/new.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'translation' %}

{% block title %}New Structure{% endblock %}

{% block body %}
    <h1>{% trans %}New{% endtrans %}</h1>

    {{ include('structure/_form.html.twig') }}

    <a class="btn btn-primary btn-lg" href="{{ path('structure_index') }}">{% trans %}back to list{% endtrans %}</a>
{% endblock %}

templates/structure/user.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'translation' %}
{% block title %}entity{% endblock %}

{% block body %}

    <div class="container-fluid p-3">

        <h1 style="text-align: center">Inspected user</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>{% trans %} Subunit{% endtrans %}</th>
                <th> {% trans %} Name{% endtrans %}</th>
                <th> {% trans %} Role{% endtrans %}</th>

                <th> {% trans %} inspection {% endtrans %}</th>
                <th> {% trans %} donejob{% endtrans %}</th>
                <th> {% trans %} restriction{% endtrans %}</th>
                <th> {% trans %} winter{% endtrans %}</th>
                <th> {% trans %} insuredevents{% endtrans %}</th>
                <th> {% trans %} reports{% endtrans %}</th>
                <th> {% trans %} flood{% endtrans %}</th>

            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.subunit.name }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.role }}</td>
                    <td>{{ user.inspection }}</td>
                    <td>{{ user.doneJobs }}</td>
                    <td>{{ user.restrictions }}</td>
                    <td>{{ user.winter }}</td>
                    <td>{{ user.insuredEvent }}</td>
                    <td>{{ user.reports }}</td>
                    <td>{{ user.flood }}</td>
                </tr>

            </tbody>
        </table>
        </div>

        <h1 style="text-align: center">Activities</h1>

        <h2 style="text-align: center;padding: 2rem" >Inpections</h2>
        <table class="table table-sm thead-dark table-bordered">
            <thead>
            <tr>
                <th style="text-align: center; vertical-align: middle"> {% trans %} RoadId {% endtrans %}</th>
                <th style="text-align: center"> {% trans %} Inspection Note {% endtrans %} </th>
                <th style="text-align: center; vertical-align: middle"> {% trans %} Inspection Date {% endtrans %} </th>
                <th style="text-align: center; vertical-align: middle"> {% trans %} RepairDate {% endtrans %} </th>
                <th style="text-align: center; vertical-align: middle"> {% trans %} Tipas {% endtrans %} </th>
                <th style="text-align: center; vertical-align: middle"> {% trans %} Username {% endtrans %} </th>
            </tr>
            </thead>
            <tbody>
            {% for inspection in inspections %}
                <tr {% if loop.index is odd %}class="color"{% endif %}>
                <tr>
                    <td style="white-space: nowrap; text-align: center; vertical-align: middle">{{ inspection.RoadId }} ({{ inspection.RoadSectionBegin }}; {{ inspection.RoadSectionEnd }})</td>
                    <td style="text-align: center; vertical-align: middle">{{ inspection.Note }} {% if inspection. IsAdditional%} ( Kelio būklė: {{ inspection.RoadCondition }}; Bangos dydis: {{ inspection.WaveSize }} cm. Vieta: {{ inspection.place }} km. ) {% endif %}</td>
                    <td style="text-align: center; vertical-align: middle">{{ inspection.RepairDate ? inspection.RepairDate|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center; vertical-align: middle">
                        {% for job in inspection.getJob %}
                            {% if job.DoneJobDate != null %}
                                <a data-placement="auto" data-toggle="tooltip" data-html="true" title="<b>Data:</b> {{ job.DoneJobDate ? job.DoneJobDate|date('Y-m-d')  : '' }} <br><b>Darbas:</b> {{ job.JobName }} <br><b>Kelias:</b> {{ job.RoadSection }} <br><b>Kiekis:</b> {{ job.Quantity }}
                            " href="{{ path('done_jobs_show', {'id': job.Id}) }}">{{ job.DoneJobDate ? job.DoneJobDate|date('Y-m-d')  : '' }}</a><br>
                            {% endif %}
                        {% endfor %}
                        <a class="btn btn-success" href="{{ path('done_jobs_add_job_to_inspection', {'id': inspection.Id}) }}">
                            <i class="fa fa-plus-circle"></i> {% trans %} Add {% endtrans %}</a>
                    <td style="text-align: center; vertical-align: middle"> {% if inspection.IsAdditional %} <p style="background-color: #F5871F; font-size: inherit; padding: 1em; margin: auto" class="fa fa-road">Sustiprinta</p> {% else %} <p style="background-color: #6b9311; font-size: inherit; padding: 1em; margin: auto" class="fa fa-road"> Patrulinė </p> {% endif %}</td>
                    <td style="text-align: center; vertical-align: middle">{{ inspection.Username }}</td>
                    <td style="text-align: center; vertical-align: middle">
                        {% include 'menu_by_roles/edit_view_inspection.html.twig' %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


        <h2 style="text-align: center;padding: 2rem">Done jobs</h2>
        <table class="table table-sm thead-dark">
            <thead>
            <tr>
                <th>{% trans %} JobId {% endtrans %}</th>
                <th>{% trans %} JobName  {% endtrans %}</th>
                <th>{% trans %} RoadSection {% endtrans %}</th>
                <th>{% trans %} RoadSectionBegin {% endtrans %}</th>
                <th>{% trans %} RoadSectionEnd {% endtrans %}</th>
                <th>{% trans %} Unit of {% endtrans %}</th>
                <th>{% trans %} Quantity {% endtrans %}</th>
                <th>{% trans %} username {% endtrans %}</th>
                <th>{% trans %} Date {% endtrans %}</th>
                <th>- </th>
                <th>{% trans %} Note  {% endtrans %}</th>
            </tr>
            </thead>
            <tbody>

            {% for done_job in done_jobs %}
                <tr {% if loop.index is odd %}class="color"{% endif %}>
                <tr>
                    <td>{{ done_job.JobId }}</td>
                    <td>{{ done_job.JobName }}</td>
                    <td>{{ done_job.RoadSection }}</td>
                    <td>{{ done_job.RoadSectionBegin }}</td>
                    <td>{{ done_job.RoadSectionEnd }}</td>
                    <td>{{ done_job.UnitOf }}</td>
                    <td>{{ done_job.Quantity }}</td>
                    <td>{{ done_job.Username }}</td>
                    <td>{{ done_job.Date ? done_job.Date|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ done_job.DoneJobDate ? done_job.DoneJobDate|date('Y-m-d') : '' }}</td>
                    <td>{{ done_job.Note }}</td>
                    <td>
                        {% include 'menu_by_roles/edit_view_done_job.html.twig' %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="13">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <h2 style="text-align: center;padding: 2rem">Winter jobs</h2>
        <table class="table">
            <thead>
            <tr>
                <th>{% trans %} CreatedAt {% endtrans %}</th>
                <th>{% trans %} Subunit {% endtrans %}</th>
                <th>{% trans %} Date {% endtrans %}</th>
                <th>{% trans %} Mechanism {% endtrans %}</th>
                <th>{% trans %} Job {% endtrans %}</th>
                <th>{% trans %} RoadSection {% endtrans %}</th>
                <th>{% trans %} Salt {% endtrans %}</th>
                <th>{% trans %} Sand {% endtrans %}</th>
                <th>{% trans %} Solution {% endtrans %}</th>
                <th>{% trans %} actions {% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for winter_job in winter_jobs | default ('') %}
                <tr>
                    <td>{{ winter_job.CreatedAt ? winter_job.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ winter_job.SubunitName }}</td>
                    <td>{{ winter_job.Date ? winter_job.Date|date('Y-m-d') : ''}}</td>
                    <td>{{ winter_job.Mechanism ? winter_job.Mechanism|join(', ') : '' }}</td>
                    <td>{{ winter_job.Job }}</td>
                    <td>{{ winter_job.getRoadSectionsStringArray| join('\n')| nl2br }}</td>
                    <td>{{ winter_job.getRoadSectionsSalt| join('\n')| nl2br }}</td>
                    <td>{{ winter_job.getRoadSectionsSand| join('\n')| nl2br }}</td>
                    <td>{{ winter_job.getRoadSectionsSolution| join('\n')| nl2br }}</td>

                    <td>
                        <a href="{{ path('winter_jobs_edit', {'id': winter_job.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="12">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <h2 style="text-align: center;padding: 2rem">Flooded roads</h2>
        <table class="table table-sm thead-dark">
            <thead>
            <tr>
                <th>{% trans %} CreatedAt {% endtrans %}</th>
                <th>{% trans %} RoadId {% endtrans %}</th>
                <th>{% trans %} RoadName {% endtrans %}</th>
                <th>{% trans %} SectionBegin {% endtrans %}</th>
                <th>{% trans %} SectionEnd {% endtrans %}</th>
                <th>{% trans %} WaterDeep {% endtrans %}</th>
                <th>{% trans %} Notes {% endtrans %}</th>
                <th>{% trans %} Status {% endtrans %}</th>
                <th>{% trans %} Subunit {% endtrans %}</th>
                <th>{% trans %} CreatedBy {% endtrans %}</th>
                <th>{% trans %} IsActive {% endtrans %}</th>
                <th>{% trans %} actions {% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for flooded_road in flooded_roads %}
                <tr>
                    <td>{{ flooded_road.createdAt | date('Y-m-d') }}</td>
                    <td>{{ flooded_road.RoadId }}</td>
                    <td>{{ flooded_road.RoadName }}</td>
                    <td>{{ flooded_road.SectionBegin }}</td>
                    <td>{{ flooded_road.SectionEnd }}</td>
                    <td>{{ flooded_road.WaterDeep }}</td>
                    <td>{{ flooded_road.Notes }}</td>
                    <td>{{ flooded_road.Status }}</td>
                    <td>{{ flooded_road.subunitId }}</td>
                    <td>{{ flooded_road.createdBy }}</td>
                    <td>{{ flooded_road.IsActive ? 'Galioja' : 'Negalioja'}}</td>
                    <td>
                        {% if is_granted('DELETE', flooded_road) %}
                            <a class="fa fa-eye btn btn-outline-primary btn-lg btn-block" href="{{ path('flooded_roads_show', {'id': flooded_road.id}) }}"></a>
                            <a class="fa fa-pencil btn btn-outline-warning btn-lg btn-block" href="{{ path('flooded_roads_edit', {'id': flooded_road.id}) }}"></a>
                        {% elseif is_granted('EDIT', flooded_road) %}
                            <a class="fa fa-eye btn btn-outline-primary btn-lg btn-block" href="{{ path('flooded_roads_show', {'id': flooded_road.id}) }}"></a>
                            <a class="fa fa-pencil btn btn-outline-warning btn-lg btn-block" href="{{ path('flooded_roads_edit', {'id': flooded_road.id}) }}"></a>
                        {% elseif is_granted('SHOW', flooded_road) %}
                            <a class="fa fa-pencil btn btn-outline-primary btn-lg btn-block" href="{{ path('flooded_roads_show', {'id': flooded_road.id}) }}"></a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    <div id="user-panel">

    </div>
{% endblock %}